jobs:
  include:
    - stage: Check linter and run tests
      language: rust
      rust:
        - 1.54.0
      before_install:
        - rustup component add rustfmt
        - rustup component add clippy-preview
      before_script:
        - cd fam_tree_rest_api
        - cargo fmt -- --check
        - cargo clippy --all-targets -- -A warnings
      script:
        - cargo build --verbose
        - cargo test --verbose
    - stage: Build docker image
      script:
        - cd fam_tree_rest_api
        - docker build . -t family_tree:1.0.0
