version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${PWD}/fam_tree_rest_api/docker-inits/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ${PWD}/fam_tree_rest_api/vault/db:/var/lib/postgresql/data
  migrator:
    build:
      context: ./fam_tree_rest_api
      target: migrator
    environment:
      PG_MIGRATIONS_DIR: /migrations
    depends_on:
      - postgres
  api:
    build:
      context: ./fam_tree_rest_api
      target: api
    environment:
      API_PORT: 5000
    depends_on:
      - postgres
      - migrator
    restart: always
    ports:
      - 5000:5000
  frontend:
    build:
      context: ./frontend
    environment:
      PORT_FRONTEND: 3000
    restart: always
    ports:
      - 3000:3000
