name: Docker Build

on: [push, pull_request]

env:
  IMAGE_REG: famtree.azurecr.io/family-tree
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1


jobs:

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: famtree.azurecr.io
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASS }}
    - name: Build builder from dockerfile
      working-directory: ./fam_tree_rest_api
      run: |
        docker build \
        --target builder \
        --cache-from $IMAGE_REG-builder:1.0.0 \
        --tag $IMAGE_REG-builder:1.0.0 \
        --file Dockerfile \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        "."
    - name: Build rest of the images
      run: docker-compose -f docker-compose.yaml -f docker-compose.prod.yaml build --build-arg BUILDKIT_INLINE_CACHE=1
    - name: Push images to acr
      if: ${{ github.event_name == 'push' }}
      run: |
        docker push $IMAGE_REG-builder:1.0.0
        docker push $IMAGE_REG-migrator:1.0.0
        docker push $IMAGE_REG-tree_api:1.0.0
        docker push $IMAGE_REG-frontend:1.0.0
